"""add message_id

Revision ID: 365d7977dc8d
Revises: a2e0ad4f2c8d
Create Date: 2025-06-27 21:11:54.453180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365d7977dc8d'
down_revision: Union[str, None] = 'a2e0ad4f2c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unfinished_operations', sa.Column('message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unfinished_operations', 'message_id')
    # ### end Alembic commands ###
